site_name: MySQL Base

site_url: http://opener.meizu.com/wiki-coding/document

docs_dir: sources

copyright: 'Copyright (c) 2016 JerryC(huangjerryc@gmail.com)'

theme: 'material'

pages:

- '总览': 'index.md'
- '1 基本概念': 'ch01/index.md'
- '2 表的操作':
  - '2.1 创建表': 'ch02/2.1.md'
  - '2.2 更新表': 'ch02/2.2.md'
  - '2.3 删除表': 'ch02/2.3.md'
- '3 数据的操作':
  - '3.1 插入数据': 'ch03/2.1.md'
  - '3.2 更新数据': 'ch03/2.2.md'
  - '3.3 删除数据': 'ch03/2.3.md'
- '4 表达式': 'ch04/index.md'
- '5 注释': 'ch05/index.md'
- '6 查询':
  - '6.1 普通查询': 'ch06/6.1.md'
  - '6.2 过滤': 'ch06/6.2.md'
  - '6.3 排序': 'ch06/6.3.md'
  - '6.4 分组': 'ch06/6.4.md'
  - '6.5 子查询': 'ch06/6.5.md'
  - '6.6 联结查询': 'ch06/6.6.md'
  - '6.7 组合查询': 'ch06/6.7.md'


- '附录':
  - '数据脚本': 'appendix/script.md'

# meterial options
extra:
  palette:
    primary: 'green'
    accent: 'light green'
  font: 'none'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

